### ISSUE TITLE
HttpResponse - AutomaticDecompression in latest Xamarin

### ISSUE THREAD

**Issue by jcbdev** [Azure/azure-mobile-apps-net-client#514]
Just updated to latest xamarin and no pull request are working on my mobile app service (working fine before).

I can see that the HttpReponse now has an Gzipped content (System.Net.Http.DecompressionHandler.GZipDecompressedContent).  I believe this is caused by the AutomaticDecompression property of HttpResponse (also possibly by setting accepted encoding types on the HttpRequest originally?)

The problem is that there is a check in the code for the contentlength property which is NULL when automatic decompression is performed by HttpResponse.  The only workaround is to check the actual header directly (apiResponse.Headers["Content-Length"]) or turn off the accepted encoding on the original request apiRequest.Headers["Accept-Encoding"]

Here is the offending code in MobileServiceHttpClient.cs:
```
if (ensureResponseContent)
            {
                long? contentLength = null;
                if (response.Content != null)
                {
                    contentLength = response.Content.Headers.ContentLength;
                }

                if (contentLength == null || contentLength <= 0)
                {
                    throw new MobileServiceInvalidOperationException("The server did not provide a response with the expected content.", request, response);
                }
            }
```

**Comment by annakocheshkova** [comment]
Hi @jcbdev, thank you for reporting this. We will look into it.

**Comment by PaoloLeva** [comment]
I get the same exception "The server did not provide a response with the expected content" as @jcbdev using latest Xamarin with all packages updated
Note that Xamarin.iOS builds work fine, no exception thrown. The problem only shows on Xamarin.Android

**Comment by RetrotecEd** [comment]
Same issue with here. Android is a problem but iOS is fine.

Few other notes: The VS debugger is broken during debugging. The exception is null in the IDE but is clearly not. You can see the following code (in picture):
![Bug](https://user-images.githubusercontent.com/25186698/65551525-041f3600-ded7-11e9-9f93-90a191d417f3.png)

It is the ToListAsync() call that fires the exception.

**Comment by jwallra** [comment]
For everyone experiencing problems, can you give the exact versions of Xamarin.Android and Visual Studio you're using?

For reference:
- [Xamarin releases](https://github.com/xamarin/xamarin-android/releases)
- [Visual studio versions](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019)

**Comment by RetrotecEd** [comment]
Microsoft Visual Studio Professional 2019
Version 16.3.0
VisualStudio.16.Release/16.3.0+29318.209
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA131
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.282.33872
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.282.33872
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.282.33872
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.3.282.33872
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.3.19252.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.10.4.8063
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

Multilingual App Toolkit   4.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.3.19252.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.3.19252.1
Conda support for Python projects.

Python - Django support   16.3.19252.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.3.19252.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.3.19252.1
Profiling support for Python projects.

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

Telerik ASP.NET Core VSExtensions   2019.3.910.1
Progress® Telerik® UI for ASP.NET Core Visual Studio extensions

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by ronnyhash** [comment]
I'm having this exact issue with Visual Studio for Mac.

Here are all my details:

=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Installation UUID: af81f3cd-68a8-430f-b5e4-520fddf2417e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
	2.0.5
	2.0.0

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/ronny/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ronny/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

=== Build Information ===

Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by norton287** [comment]
I am having the issue as well:

=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Installation UUID: 19c8c2b2-2db0-4590-9a3a-ba50296def4f
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

Package version: 604000198
=== Mono Framework MDK ===

Runtime:
Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
3.0.100
2.1.701
2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
3.0.0
2.1.13
2.1.12
2.1.11

=== Xamarin.Profiler ===

Version: 1.6.11.16
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/jnorton/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
8.0 (API level 26)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 28.0.3

Build Information:
Mono: mono/mono@7af64d1
Java.Interop: xamarin/java.interop@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip@b95cf3f
ProGuard: xamarin/proguard@905836d
SQLite: xamarin/sqlite@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jnorton/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
Tue Aug 20 16:57:14 PDT 2019
root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by ronnyhash** [comment]
Could it be related to either of these issues?

- https://github.com/mono/mono/issues/16950

- https://github.com/xamarin/xamarin-android/issues/3626

**Comment by brendanzagaeski** [comment]
This does look suspiciously similar to <https://github.com/xamarin/xamarin-android/issues/3626> to me.

If anyone on this issue gets a chance to try the following candidate workaround and reply back with whether that resolves the issue, that would be perfect. Thanks!

**Candidate workaround:**

Add a new *linker.xml* file to the Xamarin.Android app project, set the **Build Action** to **LinkDescription**, and add the following lines to it to preserve the `AndroidClientHandler` type:

```xml
<linker>
  <assembly fullname="Mono.Android">
    <type fullname="Xamarin.Android.Net.AndroidClientHandler" preserve="all" />
  </assembly>
</linker>
```

**Comment by RetrotecEd** [comment]
@brendanzagaeski  I tried it. Didn't work.

**Comment by ronnyhash** [comment]
I also tried it, and it didn't work for me either.

**Comment by brendanzagaeski** [comment]
Darn. Thanks for testing! I'll do a little more investigation from the Xamarin.Android side to see if I can help track down whether the fix will need to be in Xamarin.Android or in the Azure Mobile Apps .NET client SDK.

**Comment by PaoloLeva** [comment]
I also have this issue, here are my details:

=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Installation UUID: 644a6e7b-b593-41de-8f6c-f4f1bbcddda3
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	3.0.100-rc1-014190
	2.1.701
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	3.0.0-rc1-19456-20
	2.1.13
	2.1.12
	2.1.11

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/paololeva/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/paololeva/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

=== Build Information ===

Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by brendanzagaeski** [comment]
Cross-referencing link for the Microsoft team to the corresponding Developer Community item:
<https://developercommunity.visualstudio.com/content/problem/696459/visual-studio-preview-2-163-xamarin-android-app-er.html>

**Comment by brendanzagaeski** [comment]
I dug into this a bit more, and it looks like jcbdev's original description pinpointed the cause of the issue very nicely.

It turns out that the reason Xamarin.Android 10.0.0.43 hits this issue is that it now *correctly* sets the the `Accept-Encoding` header to `gzip` on the outbound request when `AutomaticDecompression` is set to `DecompressionMethods.GZip`. Xamarin.Android 9.4.1.1 did not correctly set that request header.

The Azure Mobile Apps .NET client SDK sets `AutomaticDecompression` to `DecompressionMethods.GZip` in:

https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L683-L686

As jcbdev correctly noted:

> the contentlength property ... is NULL when automatic decompression is performed by HttpResponse

I confirmed this quickly in a little .NET Core console app:

```
using System;
using System.Net;
using System.Net.Http;

class Program
{
    static void Main(string[] args)
    {
        var handler = new HttpClientHandler();
        handler.AutomaticDecompression = DecompressionMethods.GZip;
        var client = new HttpClient(handler);
        HttpResponseMessage response = client.GetAsync("https://www.bing.com").Result;
        Console.WriteLine(response.Content.Headers.ContentLength?.ToString() ?? "null");
    }
}
```

This prints *null*. If the `AutomaticDecompression` line is commented out, it prints a number instead.

I also confirmed that Xamarin.Android 10.0.0.43 was able to run the Xamarin.Android [quickstart example](https://github.com/Azure/azure-mobile-apps-quickstarts/tree/master/client/xamarin.android) correctly if I changed `ensureResponseContent` to `false` in the [lines jcbdev mentioned](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L618-L630). So it looks like the fix for this issue will indeed be to adjust the `MobileServiceHttpClient` implementation to expect `null` for the `ContentLength` when using `DecompressionMethods.GZip`.

**Comment by brendanzagaeski** [comment]
## Temporary workaround

Either:

  * Pass in an `HttpClientHandler` instance in the call to `new MobileServiceClient()`. Example patch for the quickstart sample:

    ```diff
    -client = new MobileServiceClient(applicationURL);
    +client = new MobileServiceClient(applicationURL, new HttpClientHandler());
    ```

    The Azure Mobile Apps .NET client SDK will not automatically set `DecompressionMethods.GZip` on the HttpClientHandler when the app provides its own in the call to `new MobileServiceClient()`, so this will restore the behavior as seen with Xamarin.Android 9.4.1.1.

  * OR pass in an instance of [`AndroidClientHandler`](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows#androidclienthandler). Example patch for the quickstart sample:

    ```diff
    -client = new MobileServiceClient(applicationURL);
    +client = new MobileServiceClient(applicationURL, new Xamarin.Android.Net.AndroidClientHandler());
    ```

    This option can potentially also improve the performance of the HTTP requests because `AndroidClientHandler` directly leverages the Android OS HTTP stack.

**Comment by jcbdev** [comment]
Nice workaround @brendanzagaeski.  

I've been using a temporary version I built myself with the response.ContentLength property check changed to check response.Content.Headers["Content-Length"] instead which _isn't_ null. 
 
It's not the _actual_ content length as it's the length of the compressed gzip stream but I believe the check is to determine there is any content at all which this revised check would do.  I could submit a PR later if that's the agreed way of resolved it?

from memory (not at my machine currently)

I have changed this:
`contentLength = response.Content.Headers.ContentLength;`

to this:
`contentLength = response.Content.Headers["Content-Length"];`

**Comment by ronnyhash** [comment]
@annakocheshkova and @jwallra  Now that this has been investigated and the root issue identified, can we get an updated nuget for Azure Mobile Client that includes a fix for this?

**Comment by ronnyhash** [comment]
@brendanzagaeski Thanks so much for digging in to find the root cause of this issue!

**Comment by jwallra** [comment]
@brendanzagaeski Thank you for your investigation and workaround! ❤️ 

I'm going to talk with the team today and see if it's possible to release an SDK update.  Ideally we would be able to mitigate the need for the workaround.

**Comment by RetrotecEd** [comment]
@brendanzagaeski Thanks Brendan, I tried the work around and we were 5/5 for doing a complete sync with the HttpClientHandler() with no issues.

Just a note, we are (were) passing in a DelegateHandler to the MobileServiceClient constructor. Hopefully an SDK update will come up and we can stick with our current code per @jwallra comment above.

**Comment by JeremyBP** [comment]
To apply the workaround AND keep custom delegate handler working, just add this to your handler constructor:
`public MyCustomDelegatingHandler() : base(new HttpClientHandler()) { }`
Best of both world :)

**Comment by ronnyhash** [comment]
After testing the work around, I'm finding that performing a sync across all my tables is about 33% slower. @jwallra we really do need a proper SDK update here that will properly address this situation. What did the team decide?

**Comment by ronnyhash** [comment]
@jcbdev Would you please share the actual code change you made to get the Content-Length value from the header? I think a change in the client is the best way to go.

**Comment by RetrotecEd** [comment]
> After testing the work around, I'm finding that performing a sync across all my tables is about 33% slower. @jwallra we really do need a proper SDK update here that will properly address this situation. What did the team decide?

I am not sure it is the handler is the cause of slowing it down. Since we updated we have seen a large decrease in performance across the board (all three platforms).

**Comment by jcbdev** [comment]
@ronnyhash @RetrotecEd @jwallra @brendanzagaeski 

I don't have my vm with all the correct dependencies installed to build this and test it but it's the same as the version I created for myself before so I believe it should work to resolve this issue.  If someone is able to test it, merge it and release a new nuget then it should solve the issue permanently!

Thanks for your help.

https://github.com/Azure/azure-mobile-apps-net-client/pull/515

**Comment by RazvanEmilR** [comment]
@brendanzagaeski Hi Brendan, I am having the same issue. What else do I need to do to make this work please?
I am creating my mobile service client like this:

 public static MobileServiceClient MobileServiceAndroid =
            new MobileServiceClient(AppConstants.AZURE_PRODUCTION_WEB_API_URL, new HttpClientHandler());

Then tried to pull from the table like this:
 if (Device.RuntimePlatform == Device.Android)
                {
                    regionList = await App.MobileServiceAndroid.GetTable<Models.Region>().ToListAsync();
                }
                else
                {
                    regionList = await App.MobileService.GetTable<Models.Region>().ToListAsync();
                }

But I assume there's a delegate class to create? Please advise how to fix this. I am still getting the error mentioned above.

**Comment by Bejasc** [comment]
Still experiencing this issue.

`Microsoft Visual Studio Community 2019
Version 16.3.1
VisualStudio.16.Release/16.3.1+29324.140
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Application Insights Tools for Visual Studio Package   9.1.00913.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.283.64955
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.283.64955
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.283.64955
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.283.64955
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.`

@jwallra can we expect an update any time soon?

**Comment by brendanzagaeski** [comment]
@RazvanEmilR, interesting. If your app was previously using a subclass of `DelegatingHandler`, then with a bit of luck, the approach JeremyBP mentioned might help:

*JeremyBP commented on Sep 28* <https://github.com/Azure/azure-mobile-apps-net-client/issues/514#issuecomment-536186635>

> To apply the workaround AND keep custom delegate handler working, just add this to your handler constructor:
> `public MyCustomDelegatingHandler() : base(new HttpClientHandler()) { }`
> Best of both world :)

* * *

Another thing you could try just to help rule out anything unexpected could be to set `AutomaticDecompression` explicitly when creating the `HttpClientHandler`:

```csharp
public static MobileServiceClient MobileServiceAndroid =
new MobileServiceClient(AppConstants.AZURE_PRODUCTION_WEB_API_URL, new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.None });
```

Lastly, it looks like `RefreshUserAsync()`, `LoginAsync()`, and `LoginWithMicrosoftAccountAsync()` are special because they don't use the `HttpClientHandler` passed to the `MobileServiceHttpClient` constructor. If your app uses one of those, then I think unfortunately there isn't a way to work around the issue without building your own *Microsoft.Azure.Mobile.Client.dll*.

**Comment by XamarinTounsi** [comment]
"The server did not provide a response with the expected content" in Android platform.
But in UWP it work well, any solution please ?

**Comment by XamarinTounsi** [comment]
what should I do here ?

````
class AuthenticationDelegatingHandler : DelegatingHandler
    {
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            // Clone the request, in case we need to re-issue it
            var clone = await CloneHttpRequestMessageAsync(request);
            // Now do the request
            var response = await base.SendAsync(request, cancellationToken);

            if (response.StatusCode == HttpStatusCode.Unauthorized)
            {
                // The request resulted in a 401 Unauthorized.  We need to do a LoginAsync,
                // which will do the Refresh if appropriate, or ask for credentials if not.
                var user = await ServiceLocator.Instance.Resolve<ICloudService>().LoginAsync();

                // Now, retry the request with the cloned request.  The only thing we have
                // to do is replace the X-ZUMO-AUTH header with the new auth token.
                clone.Headers.Remove("X-ZUMO-AUTH");
                clone.Headers.Add("X-ZUMO-AUTH", user.MobileServiceAuthenticationToken);
                response = await base.SendAsync(clone, cancellationToken);
            }

            return response;
        }

        /// <summary>
        /// Clone a HttpRequestMessage
        /// Credit: http://stackoverflow.com/questions/25044166/how-to-clone-a-httprequestmessage-when-the-original-request-has-content
        /// </summary>
        /// <param name="req">The request</param>
        /// <returns>A copy of the request</returns>
        public static async Task<HttpRequestMessage> CloneHttpRequestMessageAsync(HttpRequestMessage req)
        {
            HttpRequestMessage clone = new HttpRequestMessage(req.Method, req.RequestUri);

            // Copy the request's content (via a MemoryStream) into the cloned object
            var ms = new MemoryStream();
            if (req.Content != null)
            {
                await req.Content.CopyToAsync(ms).ConfigureAwait(false);
                ms.Position = 0;
                clone.Content = new StreamContent(ms);

                // Copy the content headers
                if (req.Content.Headers != null)
                    foreach (var h in req.Content.Headers)
                        clone.Content.Headers.Add(h.Key, h.Value);
            }


            clone.Version = req.Version;

            foreach (KeyValuePair<string, object> prop in req.Properties)
                clone.Properties.Add(prop);

            foreach (KeyValuePair<string, IEnumerable<string>> header in req.Headers)
                clone.Headers.TryAddWithoutValidation(header.Key, header.Value);

            return clone;
        }
    }
````

**Comment by jwdb** [comment]
@XamarinTounsi Add a new constructor like this:

`public AuthenticationDelegatingHandler() : base(new HttpClientHandler()) { }`

**Comment by XamarinTounsi** [comment]
````
 public AuthenticationDelegatingHandler() : base(new HttpClientHandler()) 
        
        {

        }
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            // Clone the request, in case we need to re-issue it
            var clone = await CloneHttpRequestMessageAsync(request);
            // Now do the request
            var response = await base.SendAsync(request, cancellationToken);

            if (response.StatusCode == HttpStatusCode.Unauthorized)
            {
                // The request resulted in a 401 Unauthorized.  We need to do a LoginAsync,
                // which will do the Refresh if appropriate, or ask for credentials if not.
                var user = await ServiceLocator.Instance.Resolve<ICloudService>().LoginAsync();

                // Now, retry the request with the cloned request.  The only thing we have
                // to do is replace the X-ZUMO-AUTH header with the new auth token.
                clone.Headers.Remove("X-ZUMO-AUTH");
                clone.Headers.Add("X-ZUMO-AUTH", user.MobileServiceAuthenticationToken);
                response = await base.SendAsync(clone, cancellationToken);
            }

            return response;
        }

        /// <summary>
        /// Clone a HttpRequestMessage
        /// Credit: http://stackoverflow.com/questions/25044166/how-to-clone-a-httprequestmessage-when-the-original-request-has-content
        /// </summary>
        /// <param name="req">The request</param>
        /// <returns>A copy of the request</returns>
        public static async Task<HttpRequestMessage> CloneHttpRequestMessageAsync(HttpRequestMessage req)
        {
            HttpRequestMessage clone = new HttpRequestMessage(req.Method, req.RequestUri);

            // Copy the request's content (via a MemoryStream) into the cloned object
            var ms = new MemoryStream();
            if (req.Content != null)
            {
                await req.Content.CopyToAsync(ms).ConfigureAwait(false);
                ms.Position = 0;
                clone.Content = new StreamContent(ms);

                // Copy the content headers
                if (req.Content.Headers != null)
                    foreach (var h in req.Content.Headers)
                        clone.Content.Headers.Add(h.Key, h.Value);
            }


            clone.Version = req.Version;

            foreach (KeyValuePair<string, object> prop in req.Properties)
                clone.Properties.Add(prop);

            foreach (KeyValuePair<string, IEnumerable<string>> header in req.Headers)
                clone.Headers.TryAddWithoutValidation(header.Key, header.Value);

            return clone;
        }
``````
In AzureCloudService i have added this

`````
 public AzureCloudService()
        {
            Client = new MobileServiceClient(Locations.AppServiceUrl, new AuthenticationDelegatingHandler(), new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.None });
            if (Locations.AlternateLoginHost != null)
            {
                Client.AlternateLoginHost = new Uri(Locations.AlternateLoginHost);
            }
            PlatformProvider = DependencyService.Get<IPlatformProvider>();
            if (PlatformProvider == null)
            {
                throw new InvalidOperationException("No Platform Provider");
            }
        }
````
Still not work in Android Platform

**Comment by jwdb** [comment]
@XamarinTounsi Since you already have a HttpClientHandler in the constructor of the MobileServiceClient, you don't need the constructor in the DelegatingHandler. 

Does it still give the exact same error or did it change?

Make sure the HTTP request also doesn't contain a `Accept-Encoding: GZip` since that could trigger the same bug as xamarin/xamarin-android#3626.

Also make sure your Visual Studio version is 16.3.3+ to fix issue Mono/Mono#16950.

This issue is one big rabbithole that went wrong on multiple levels...

**Comment by XamarinTounsi** [comment]
Now i have this error, "You must pass in a corretly formated url".

**Comment by XamarinTounsi** [comment]
to avoid all doubts, i have added a Linker.xml file 
````
<?xml version="1.0" encoding="utf-8" ?> 
<linker>
  <assembly fullname="Mono.Android">
    <type fullname="Xamarin.Android.Net.AndroidClientHandler" preserve="all" />
  </assembly>
</linker>
````
in csproj, i have added 
````
<ItemGroup>
  <LinkDescription Include="YourLinkDescriptionFileName.xml" />
</ItemGroup>
````
i did like @brminnick
![image](https://user-images.githubusercontent.com/52005714/66648374-a8b9ab80-ec2b-11e9-8633-b448d2b2a54f.png)
````
Still same error ...

**Comment by asierpn** [comment]
Same error here after upgrading to VS 16.3 and Xamarin.Android 10.0, at this moment I'm using VS 16.3.4 and Xamarin.Android 10.0.3.0 and the issue is still happening.

**Comment by RazvanEmilR** [comment]
Any updates on this? What is the solution after all?

**Comment by jcbdev** [comment]
@RazvanEmilR @asierpn @XamarinTounsi 

I submitted a pull request for this to fix in this nuget package but had no reply or anything ?!?
(PR here -> https://github.com/Azure/azure-mobile-apps-net-client/pull/515).

I tried **¯\\_(ツ)_/¯**

There is another workaround for anyone who controls the api end.  I probably wouldn't recommend this but if you are struggling as some of my mobile teams are then this has been used to work around it.

This avoids gzip entirely so should give the same performance as the original behaviour.

Web Api (Global.asax.cs)
```
protected void Application_BeginRequest(object sender, EventArgs e)
{
    try
    {
        HttpContext.Current.Request.Headers["Accept-Encoding"] = "";
    }
    catch(Exception){}
}
```

.net core (middleware)
```
public class RemoveGzipRequestContentEncodingMiddleware
{
    public RemoveGzipRequestContentEncodingMiddleware(RequestDelegate next)
    {
        if (next == null)
            throw new ArgumentNullException(nameof(next));

        this.next = next;
    }

    private readonly RequestDelegate next;
    private const string ContentEncodingHeader = "Content-Encoding";

    public async Task Invoke(HttpContext context)
    {
        if (context.Request.Headers.Keys.Contains(ContentEncodingHeader))
        {
            var contentEncoding = context.Request.Headers[ContentEncodingHeader];
            context.Request.Headers.Remove(ContentEncodingHeader);
        }

        await next(context);
    }
}
```

**Comment by asierpn** [comment]
@RazvanEmilR the only solution at this time for us is keep using VS 16.2.4 to work with Azure Mobile App from Xamarin.Android

**Comment by XamarinTounsi** [comment]
i had this error now, Error loading items: You must pass in a corretly formated url.

**Comment by XamarinTounsi** [comment]
![image](https://user-images.githubusercontent.com/52005714/67010223-8b825280-f0ed-11e9-9aa0-d33103b2dc9f.png)

**Comment by XamarinTounsi** [comment]
Before upgrading it work perfectly ? why

**Comment by asierpn** [comment]
It seems that the bug was introduced in Xamarin.Android 10.0 which is included in VS 16.3, if you revert to VS 16.2 you will avoid this issue.

**Comment by XamarinTounsi** [comment]
The problem is present on all platforms not just in Android

**Comment by asierpn** [comment]
In our case the issue is only happening from Xamarin.Android, Xamarin.iOS and UWP are working fine after upgrading to 16.3 as @PaoloLeva commented.

**Comment by norton287** [comment]
When will an official fix be pushed out.  I know that @jcbdev has a PR with a resolution, why hasn't anyone acted on this yet?

**Comment by Bejasc** [comment]
@dhei please review this thread and consider merging @jcbdev 's [pull request](https://github.com/Azure/azure-mobile-apps-net-client/pull/515).

**Comment by ChaseFlorell** [comment]
looks like #515 is waiting to go.

**Comment by dhei** [comment]
Hey folks,

Sorry for the delay in response.

We plan to release a fix for this issue and we will share the ETA of the release as soon as we have one.

**Comment by ChaseFlorell** [comment]
Hey @dhei, I recognize that there are processes required in order to get a release out the door, but I'm wondering if there is anything we can do in the mean time in order to remove the impediment.

For myself, I've done exactly what was described above, but it has not circumvented the issue

```csharp
        public AuthenticationDelegatingHandler(
            IAuthService authService, 
            IVersionTracking versionTracking):base(new HttpClientHandler())
        {
```

**Comment by rkshnair** [comment]
@dhei Any Updates????

**Comment by norton287** [comment]
What is the status of the release, I see the PR has been approved but not merged.  Can we get a time frame to work with as far as fixing this issue?

**Comment by ChaseFlorell** [comment]
@dhei, I don't believe this is something y'all should just be sitting on. With no easy rollback option with Visual Studio, the only path is a path forward. This is now a major impediment that needs addressing. Please escalate this issue and get it resolved!

**Comment by stezma** [comment]
Microsoft want to promote App Center Data now, and they don't want to give support to this library anymore. If you look into the azure portal they have remove the option to create Mobile App Service as well. 

These people are really crazy, at some point of time they will stop App Center Data as well. Who knows how long they even support Xamarin..... Ridiculous  :/

**Comment by ChaseFlorell** [comment]
@stezma technology will always be deprecated and replaced. This is a fact of progress. I'm perfectly ok with them stopping new feature development on this product... what we do need however is critical fixes and maintenance releases for a period of time after support is dropped.

**Comment by ahbilal-ms** [comment]
Apologies for the delayed respond and all the inconvenience this is causing. You all have raised some valid points and I will make sure your voices gets heard within Microsoft. We definitely need to get better in migrating people from one platform to another.  As for this issue, we do plan to fix it but the release/shipment is expected to happen by December. And while we have fixed the issue, we still have to do some testing before we release the SDK.

**Comment by ChaseFlorell** [comment]
>As for this issue, we do plan to fix it but the release/shipment is expected to happen by December
yikes!

as I said before, MS has made it really difficult to roll back our environments once they're updated, so a breaking change like this become orders of magnitude more difficult to mitigate.

**Comment by ahbilal-ms** [comment]
@ChaseFlorell Thanks for the note! I will keep on pushing to release it early! I have shared the tentative plan but hopefully we will try to get it release early.

**Comment by jcbdev** [comment]
@ahbilal-ms Are you seriously suggesting it will take another month?  I think you'll find lots of people are affected by this and losing money in wasted time and customers.  There are live systems using this library!

What else is in this next release that needs such extensive and testing and quality control that you can't release a pre-release package immediately? Wouldn't it be more efficient to release it as a prerelease package and let us (the community) test it for you?

I think I am not the only person experiencing major frustration with the response to this issue.  Especially as I highlighted the exact bug (and lines of code) in the first post on the 24th September.

**Comment by stezma** [comment]
@ChaseFlorell I am also asking the same thing. Why there is no support.
MS is making things deprecated only for looting money. What extra feature / security they have introduced in App Center Data?
It is still buggy and not matured enough to replace  Azure Mobile Apps.

**Comment by asierpn** [comment]
We use Azure Mobile Apps to connect to various on-premises SQL databases and we use also offline sync, I think that App Center Data is far to provide such features so Azure Mobile Apps can not be deprecated until Microsoft give us an alternative service and migration instructions.

**Comment by Bejasc** [comment]
> 
> 
> We use Azure Mobile Apps to connect to various on-premises SQL databases and we use also offline sync, I think that App Center Data is far to provide such features so Azure Mobile Apps can not be deprecated until Microsoft give us an alternative service and migration instructions.

This, 100%. 
It's very concerning that MS have dropped Azure Mobile Apps like a hot stone, without providing adequate alternatives, instruction, or support. Especially as so many of us are experiencing this issue in a production environment. 

@ahbilal-ms Is there really no cause here to fast-track this release?

**Comment by jcbdev** [comment]
@ahbilal-ms These are very good points from @Bejasc and @asierpn I think should be considered harder.  I think you may be underestimating the impact to companies relying on this library which cannot just switch on a whim.

It's my understanding as well that App Center Data is still in _preview_ and it forces you to use cosmos db which not every application can be moved to trivially. Especially as intergrations with other platforms for cosmos db is still lacking in many areas (The terrible Power BI connector comes to mind which you can't even use on powerbi.com).

**Comment by Bejasc** [comment]
> 
> It's my understanding as well that App Center Data is still in _preview_ and it forces you to use cosmos db which not every application can be moved to trivially. 

This in particular is why MS stance on this is concerning me. We've already migrated over from MySql to SQL Server a little over 18 months ago, just so that we could use this library. It took us a good 6 months to prepare, build, and fully test for the data migration alone, let alone the time taken (and still taken, with other issues we are dealing with in this library), it damn near killed our product. 

The idea of having to go through that process again so soon, just so that we can continue using supported tech - is frightening.

**Comment by ahbilal-ms** [comment]
Thanks for sharing your concerns. I will escalate this issue to the highest level and will come back to you with an update by end of day. Thanks

**Comment by swift-nicholas** [comment]
@ahbilal-ms Does Microsoft seriously expect people to transition from table controllers to a App Center Data implementation? Like others in this issue, we have the azure apps sdk deployed in production that services a large number of clients, can can't just change a core aspect of our stack. What confidence can Microsoft provide that the same fate won't happen to App Center Data services?

**Comment by ChaseFlorell** [comment]
@ahbilal-ms how did the escalation go?

**Comment by ahbilal-ms** [comment]
Hey All! I did escalate the issue but we are still looking at the timeline of early December for the SDK release. I understand the frustration and concerns that many of you have raised but considering the backlog of work we have, it is difficult to commit anything before December. The team however is committed to resolve this and other issues associated with Azure Mobile Services. Also, I will keep on pushing the team on this issue and if we do find any opportunity to fix it earlier, we will definitely do that.

**Comment by rkshnair** [comment]
@brendanzagaeski 
I have created a Dependency Service in Platform level

**Android**
```
 public HttpMessageHandler GetHttpHandler()
 {
     return new AndroidClientHandler();
 }
```
**IOS**
```
 public HttpMessageHandler GetHttpHandler()
 {
      return new NSUrlSessionHandler();
 }

```

**And in Forms I am assigning the handler like this**
```

 var handler = PlatformHandler.GetHttpHandler() ?? new HttpClientHandler();
 Client = new MobileServiceClient(_config.AzureMobileServiceUri.AzureMobileAppUri, handler);
```
All the happy flow scenarios it is working fine. But in the workaround you provided, it has mentioned that 

 _These workarounds won't fully resolve the issue for apps that use the RefreshUserAsync(), **LoginAsync()**, or **LoginWithMicrosoftAccountAsync()** method of **MobileServiceHttpClient** because those methods use their own **HttpClientHandler** instance rather than the one passed into the constructor._

So my doubt is,

In my app I am calling the LoginAsync() method, Is it going to fail at any circumstances? If yes what I can do to fix it?

`Client?.LoginAsync(MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory, objToken);`

**Comment by brendanzagaeski** [comment]
> In my app I am calling the LoginAsync() method, Is it going to fail at any circumstances? If yes what I can do to fix it?

As a caution, I'm not an expert on the Azure Mobile Apps .NET client SDK. That caution out of the way, the background for my comment about `LoginAsync()` is that I looked at the call path through the following methods:

 1. [`MobileServiceClient.LoginAsync()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/MobileServiceClient.cs#L391-L400)
 2. [`MobileServiceAuthentication.LoginAsync()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Authentication/MobileServiceAuthentication.cs#L140-L153)
 3. [`MobileServiceTokenAuthentication.LoginAsyncOverride()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Authentication/MobileServiceTokenAuthentication.cs#L56-L70)
 4. [`MobileServiceHttpClient.RequestWithoutHandlersAsync()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L169-L174)
 5. [`MobileServiceHttpClient.RequestAsync()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L248-L294), with a value of `false` in the `UseHandlers` parameter, and a value of `false` in the `ensureResponseContent` parameter
 6. [The initialization of `MobileServiceHttpClient.httpClientSansHandlers`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L133)
 7. [`MobileServiceHttpClient.DefaultHandlerFactory()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L107)
 8. [`MobileServiceHttpClient.GetDefaultHttpClientHandler()`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L680-L689)

Based on my reading of that call path, `MobileServiceClient.LoginAsync()` will always use an `HttpClientHandler` instance that has `HttpClientHandler.AutomaticDecompression` set to `DecompressionMethods.GZip` in Xamarin.Android applications because `HttpClientHandler.SupportsAutomaticDecompression` will be `true` at <https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L683>.

But I think when I originally looked at this a few weeks ago I missed the detail that `ensureResponseContent` is `false` at step 5. When `ensureResponseContent` is `false`, [the code path that checks the value of `response.Content.Headers.ContentLength` and throws `MobileServiceInvalidOperationException`](https://github.com/Azure/azure-mobile-apps-net-client/blob/4.1.1/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs#L618-L630) will be skipped, and the login will proceed successfully.

Given this reassessment, I think my comment about limitations for `RefreshUserAsync()`, `LoginAsync()`, and `LoginWithMicrosoftAccountAsync()` can be ignored. I think all of those methods will work.

**Comment by norton287** [comment]
Anyone update us with a release time for this month?

**Comment by RazvanEmilR** [comment]
@norton287 I would like to know as well.

**Comment by ahdbilal** [comment]
This is in active development and the team is expected to release the SDK any time in the next few days. I will get an another update in the morning and will post it here.

**Comment by Bejasc** [comment]
@ahdbilal can you please provide an update as mentioned?

**Comment by ahdbilal** [comment]
This work is now completed and has been shipped in v4.1.2 of the client. These can be accessed from the below link:
https://github.com/Azure/azure-mobile-apps-net-client/releases/tag/4.1.2
https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/4.1.2
https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client.SQLiteStore/4.1.2

**Comment by rachael-ross** [comment]
Thank you!!!

**Comment by devperson** [comment]
Thanks, new package version works, but it does not compile in Azure CI for some reason, see attached logs
[errLog.txt](https://github.com/Azure/azure-mobile-apps-net-client/files/3960537/errLog.txt)

**Comment by MatkovIvan** [comment]
Hi @devperson, 

This method (from your logs), hasn't been changed in this release. Please open separate issue because it's unrelated to this one. Thanks.

**Comment by FlxGen** [comment]
This error is back.  Perhaps the headers from the server have changed.

Wouldn't it be better/easier to inspect the content later?  Perhaps in the GetResponseContent method?  I don't think there would be any downstream issues since the other methods calling the SendRequestAsync method have ensureResponseContent set to false.  

Or maybe some fancier handling when the content type is application/json.

        private static async Task<string> GetResponseContent(HttpResponseMessage response)
        {
            string responseContent = null;
            if (response.Content != null)
            {
                responseContent = await response.Content.ReadAsStringAsync();
            }

            if (responseContent == null)
            {
                throw new Exception("The server did not provide a response with the expected content.");
            }
            return responseContent;
        }

**Comment by olmisa** [comment]
Hi @FlxGen ,
is it possible to provide more details about the error? I mean maybe there are exact repro steps? 
Also, here we have workarounds https://github.com/Azure/azure-mobile-apps-net-client/issues/514/#issuecomment-535297742 . These workarounds are work for you?
I'm interested in why you wrote only about JSON type?
Am I right that the main problem is that 'response.Content' is null in several cases (the fix was provided for the case when 'response.Headers.ContentLength' is null)?

Thanks.

**Comment by Jan-NET** [comment]
I am wondering if this bug was ever away. 
The combination VS 16.2.3 and Mobile Service Client 4.1.1 works fine, as in August/September 2019. If I make a little upgrade step to VS 16.3.0 in combination with Mobile Service Client 4.1.1 the exception "The server did not provide a response with the expected content." shows up. That was expectable. 
If I update to Mobile Service Client 4.1.2 the exception is still there. (In detail: Microsoft.WindowsAzure.MobileServices.MobileServiceInvalidOperationException: The server did not provide a response with the expected content.  at Microsoft.WindowsAzure.MobileServices.MobileServiceHttpClient.SendRequestAsync).

The fix #526 „Fix the validation of HTTP responses with AutomaticDecompression enabled“ in MobileServiceHttpClient.cs is most likely without effect.
Let’s review the code changes for fix #526 in azure-mobile-apps-net-client/src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs (and we keep in mind that the http-response with compression and contentLength = null caused the exception): 
First `IsDecompressionUsed(HttpRequestMessage request)` detects the compression state. By the way: Why is this determined by the request header and not by the response header? Even if the client sends `"Accept-Encoding"` the server may choose not to compress the response and the result from `IsDecompressionUsed `is wrong. 
Anyway, when we assume that a compression is used we can never run in code line 638 to 645 to raise the exception. I didn't get the trick yet, see here:
```
bool decompressionUsed = IsDecompressionUsed(request);

if (!decompressionUsed && response.Content != null)
{
	long? contentLength = response.Content.Headers.ContentLength;
	if (contentLength == null || contentLength <= 0)
	{
		throw new MobileServiceInvalidOperationException("The server did not provide a response with the expected content.", request, response);
	}
}
```
The only conclusion would be that the result from `IsDecompressionUsed` is wrong and `contentLength = null` or `response.Content.Headers.ContentLength` crashes.
Unfortunately without code acrobatics it is not possible to inspect the HTTPS-Traffic from an Android-Device due to MobileServiceHttpClient is bypassing the Fiddler-proxy so I can´t deliver any traffic details. If I look in the network traces in the mobile service backend, I would say compression is used and content length is set. 
When I use the backend with Postman and play around with the encoding, the content length is always set.
I guess the JSON thing from @FlxGen is misleading.

**Comment by annakocheshkova** [comment]
Hey @Jan-NET I think you might be onto something here. Indeed, [the server may choose](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) when to use it himself. In this case, we also need to check "Content-Encoding" in response. I'll re-open this bug.

**Comment by Jan-NET** [comment]
Hi @annakocheshkova, 
thank you for your fast response. 
I got the source code from Mobile Service Client up and running in my project and while debugging the situation is like this: In the HTTP-request is no `„Accept-Encoding“` header. I don‘t know why!
In the HTTP-response is only the `„Vary: Accept-Encoding“` header, not the `„Content-Encoding“` header; `response.Content.Headers.ContentLength` is null so the raised MobileServiceInvalidOperationException is logical.

As far as I understand if the server responds with `„Vary: Accept-Encoding“` the encoding varies indirectly by the value in `„Accept-Encoding“` from the request. Probably means if the request accepts gzip and the server responds `„Vary: Accept-Encoding“` you can assume that the content is encoded with gzip. 
The following code would work if it’s for sure the any encoding is accepted by the client. But I don’t like code that assume somewhat is for sure. Actually, the request must also be taken into account (like in the current version of `IsDecompressionUsed`), but without a header...
```
 private static bool IsDecompressionUsed(HttpResponseMessage response)
        {
            IEnumerable<string> EncodingList;
            response.Headers.TryGetValues("Content-Encoding", out EncodingList);
            if (EncodingList == null)
            {
                // check for Vary header
                IEnumerable<string> VaryList;
                response.Headers.TryGetValues("Vary", out VaryList);
                if (VaryList == null)
                {
                    return false;
                }
                else
                {
                    string allVaryValues = VaryList.Aggregate((allValues, next) => allValues = allValues + ";" + next);
                    return !string.IsNullOrEmpty(allVaryValues) && (allVaryValues.Contains("Accept-Encoding"));
                }
            }
            else
            {
                string allEncodingValues = EncodingList.Aggregate((allValues, next) => allValues = allValues + ";" + next);
                return !string.IsNullOrEmpty(allEncodingValues) &&
                     (allEncodingValues.Contains("gzip") ||
                     allEncodingValues.Contains("deflate") ||
                     allEncodingValues.Contains("br") ||
                     allEncodingValues.Contains("compress"));
            }
        }
```

**Comment by jcbdev** [comment]
@Jan-NET Does my original PR work? It didn't have the IsDecompressionUsed() check.

https://github.com/Azure/azure-mobile-apps-net-client/pull/515/files

**Comment by annakocheshkova** [comment]
@Jan-NET 
Yes, my initial idea was to check both request and response for this value.

I've read several pages about this “Vary” keyword and basically it ensures that the requested resource would not be loaded from cache if the header value is different. So if a compressed resource is stored in cache and the request does not accept encoding, a new page will be returned. The most understandable explanation I found is [here](https://stackoverflow.com/a/7848882/7453375).
They also say that the “Content-Encoding” is not enough in this case, but yeah, worth checking anyway.

In any case, thanks for the snippet and the debugging! Will be very helpful.

**Comment by Jan-NET** [comment]
Hi @jcbdev, 
no, it doesn’t work! 
`response.Content.Headers.TryGetValues` results in false because the header field `Content-Length` is not in the response. So the default value `null` for `contentLength` is passed to the null-check and the exception raises. 
If you want to guard against the missing content-length header why then the check against null is still necessary?
If I use the mobile client in an UWP-App against the same backend it works fine. The `Content-Length` is in the response header and `Accept-Encoding` is in the request. 

I'm afraid we're playing in the wrong place. Which layer discards the header information in the android environment?

**Comment by Jan-NET** [comment]
@annakocheshkova 
As I wrote to @jcbdev the mobile client behavior between the several environments is not consistent. 
Based on this it is questionable whether we can get a robust check. 
Who knows the whole traffic pipeline?

**Comment by FlxGen** [comment]
@Jan-NET This is why I attempt read the content regardless of what the header says as a work around.  We are expecting content in these methods anyways so if the result of GetResponseContent() is null then I throw.  

I agree there seems to be some inconsistency in the headers.  I wasn't able to figure out why but I think it's related to requests sent to the server and a new/updated server config or change to one or more classes in System.Net.Http.  

What I found is that when the client creates requests after a fresh install, I get the proper response headers.  If I quit the app and try again, I don't.  There must be some mechanism that existed prior to whatever changed on the server side that causes this but the server no longer masks the bug. 

I'll remove my work around and generate the request again so everyone can compare fresh install requests and after quitting the app.  Probably won't be until next week.

**Comment by Jan-NET** [comment]
@FlxGen 
According to my latest findings I agree with you that we can get rid of the header problems with the later response check in `GetResponseContent()`.
May your appearances (fresh install, restart app) have to do with a cache on the server side or a proxy?
If I test/check my mobile service backend with Fiddler or Postman the responses shows a consistent picture. I trust the responses from the server, but not the processing in the client!
Unfortunately, I lack the knowledge of how Mono / .NET / Xamarin interact on an Android device and where to hook in for further debugging.

**Comment by adrianhall** [comment]
This is fixed in PR #554, which was just merged into master.  It will be released in the next couple of weeks as v4.2.0
